In [38]:
import tensorflow as tf

In [39]:
# Define input image and filter
input_image = tf.constant([[[[1.0], [2.0], [3.0], [4.0]],
                            [[5.0], [6.0], [7.0], [8.0]],
                            [[9.0], [10.0], [11.0], [12.0]],
                            [[13.0], [14.0], [15.0], [16.0]]]], dtype=tf.float32)
filter_weights = tf.constant([[[[1.0]], [[0.0]]],
                              [[[0.0]], [[1.0]]]], dtype=tf.float32)

In [40]:
# Apply convolution with padding
output_padded = tf.nn.conv2d(input_image, filter_weights, strides=[1, 1, 1, 1], padding='SAME')

# Print the padded output
print(output_padded)

tf.Tensor(
[[[[ 7.]
   [ 9.]
   [11.]
   [ 4.]]

  [[15.]
   [17.]
   [19.]
   [ 8.]]

  [[23.]
   [25.]
   [27.]
   [12.]]

  [[13.]
   [14.]
   [15.]
   [16.]]]], shape=(1, 4, 4, 1), dtype=float32)


In [41]:
dropout_rate = 0.5

# Apply dropout
output_dropout = tf.nn.dropout(input_image, rate=dropout_rate)

# Print the output with dropout
print(output_dropout)

tf.Tensor(
[[[[ 2.]
   [ 0.]
   [ 6.]
   [ 8.]]

  [[10.]
   [12.]
   [ 0.]
   [ 0.]]

  [[ 0.]
   [ 0.]
   [22.]
   [24.]]

  [[26.]
   [28.]
   [30.]
   [32.]]]], shape=(1, 4, 4, 1), dtype=float32)


In [42]:
# Apply batch normalization
output_normalized = tf.nn.batch_normalization(input_image, mean=0, variance=1, offset=None, scale=None, variance_epsilon=1e-8)

# Print the normalized output
print(output_normalized)

tf.Tensor(
[[[[ 1.]
   [ 2.]
   [ 3.]
   [ 4.]]

  [[ 5.]
   [ 6.]
   [ 7.]
   [ 8.]]

  [[ 9.]
   [10.]
   [11.]
   [12.]]

  [[13.]
   [14.]
   [15.]
   [16.]]]], shape=(1, 4, 4, 1), dtype=float32)
